config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  get 'profile' => 'users#edit'
  patch 'profile' => 'users#update'
  get 'password' => 'users#edit_password'
  post 'password' => 'users#update_password'

  post 'login' => 'session#create'
  post 'logout' => 'session#destroy'

  resources :vehicles do
    resources :fuelings
    resources :maintenance
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :vehicles

  validates :email, uniqueness: true

  def gravatar_hash
    gravatar_email = email.strip.downcase

    digest = Digest::MD5.new
    digest.update gravatar_email

    digest.hexdigest
  end
end

app/controllers/users_controller.rb
require 'Session'

class UsersController < ApplicationController
  def get
    session_manager = Session.new(session)

    unless session_manager.logged_in?
      return head :unauthorized
    end

    @profile = session_manager.user
  end

  def create
    inputs = register_params
    @new_user = User.create(inputs)

    if @new_user.invalid?
      return render json: @new_user.errors.details, status: 422
    end

    session_manager = Session.new(session)
    session_manager.login @new_user
  end

  def update
    update_params = profile_params
    session_manager = Session.new(session)
    unless session_manager.logged_in?
      return head :unauthorized
    end

    @updated_user = session_manager.user
    @updated_user.update update_params
  end

  def update_password
    update_params = password_params
    session_manager = Session.new(session)
    unless session_manager.logged_in?
      return head :unauthorized
    end

    @updated_user = session_manager.user
    @updated_user.update update_params
    return head :no_content
  end

  private

  def register_params
    params.permit(:email, :name, :password, :password_confirmation)
  end

  def profile_params
    params.permit(:email, :name)
  end

  def password_params
    params.permit(:password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="profile form">
  <%= form_for @user, url: profile_path do |f| %>
    <div class="form-group">
      <%= f.label :name, class: 'control-label' %>:
      <%= f.text_field :name, value: @user.name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, class: 'control-label' %>:
      <%= f.text_field :email, value: @user.email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success" %>
      <a href="<%= password_path %>" class="btn btn-default">Change password</a>
    </div>
  <% end %>
</div>

app/views/users/show_password.html.erb
<div class="profile form">
  <%= form_tag url: profile_path, method: 'POST' do %>
    <div class="form-group">
      <%= label_tag :password, 'Password: ', class: 'control-label' %>
      <%= password_field_tag :password, nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :password_confirmation, 'Password confirmation: ', class: 'control-label' %>
      <%= password_field_tag :password_confirmation, nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag "Save", class: "btn btn-success" %>
    </div>
  <% end %>
</div>