config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  get 'profile' => 'users#edit'
  patch 'profile' => 'users#update'
  get 'password' => 'users#edit_password'
  post 'password' => 'users#update_password'

  post 'login' => 'session#create'
  post 'logout' => 'session#destroy'

  resources :vehicles do
    resources :fuelings
    resources :maintenance
  end
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
  belongs_to :vehicle

  def needs_attention?
    return vehicle.last_maintenance == self if vehicle.needs_maintenance?
    false
  end
end

app/controllers/maintenance_controller.rb
class MaintenanceController < AuthorizeVehicleController
  before_action :fetch_maintenance, except: [:create]

  def initialize
    super(:vehicle_id)
  end

  def create
    @new_maintenance = Maintenance.create maintenance_params.merge(vehicle_id: params[:vehicle_id])
  end

  def update
    @maintenance.update maintenance_params
  end

  def destroy
    @maintenance.destroy
    head :no_content
  end

  private

  def fetch_maintenance
    @maintenance = Maintenance.find params[:id]
  end

  def maintenance_params
    params.require(:maintenance).permit(:date, :description, :mechanic, :cost)
  end
end

app/views/maintenance/new.html.erb
<div class="maintenance form">
  <h3>
    <i class="fa fa-wrench"></i> New maintenance
  </h3>
  <%= form_for @maintenance, url: vehicle_maintenance_index_path do |f| %>
    <div class="form-group">
      <%= f.label :date, class: 'control-label' %>:
      <%= f.text_field :date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :mechanic, class: 'control-label' %>:
      <%= f.text_field :mechanic, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :cost, class: 'control-label' %>:
      <%= f.text_field :cost, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description, class: 'control-label' %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Add', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>