config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  get 'profile' => 'users#edit'
  patch 'profile' => 'users#update'
  get 'password' => 'users#edit_password'
  post 'password' => 'users#update_password'

  post 'login' => 'session#create'
  post 'logout' => 'session#destroy'

  resources :vehicles do
    resources :fuelings
    resources :maintenance
  end
end

app/models/fueling.rb
class Fueling < ApplicationRecord
  belongs_to :vehicle

  validates :date, presence: true

  def mpg
    miles / gas
  end

  def above_average_mpg?
    mpg > vehicle.lifetime_mpg
  end

  def below_average_mpg?
    mpg < vehicle.lifetime_mpg
  end
end

app/controllers/fuelings_controller.rb
class FuelingsController < AuthorizeVehicleController
  before_action :fetch_fueling, except: [:create]

  def initialize
    super(:vehicle_id)
  end

  def create
    @new_fueling = Fueling.create fueling_params.merge(vehicle_id: params[:vehicle_id])
  end

  def update
    @fueling.update fueling_params
  end

  def destroy
    @fueling.destroy
    head :no_content
  end

  private

  def fetch_fueling
    @fueling = Fueling.find params[:id]
  end

  def fueling_params
    params.permit(:date, :gas, :miles, :cost, :description)
  end
end

app/views/fuelings/new.html.erb
<div class="fueling form">
  <%= form_for @fueling, url: vehicle_fuelings_path do |f| %>
    <div class="form-group">
      <%= f.label :date, class: 'control-label' %>:
      <%= f.text_field :date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :gas, 'Gallons of gas: ', class: 'control-label' %>
      <%= f.text_field :gas, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :cost, class: 'control-label' %>:
      <%= f.text_field :cost, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :miles, class: 'control-label' %>:
      <%= f.text_field :miles, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description, class: 'control-label' %>:
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Add', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>