config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  get 'profile' => 'users#edit'
  patch 'profile' => 'users#update'
  get 'password' => 'users#edit_password'
  post 'password' => 'users#update_password'

  post 'login' => 'session#create'
  post 'logout' => 'session#destroy'

  resources :vehicles do
    resources :fuelings
    resources :maintenance
  end
end

app/models/vehicle.rb
require 'enumerable'

class Vehicle < ApplicationRecord
  belongs_to :user

  has_many :fuelings
  has_many :maintenance

  def needs_maintenance?
    last_maintenance.nil? ||
      last_maintenance.date < 6.months.ago ||
      miles_since_maintenance > 4000
  end

  def lifetime_mileage
    computed_miles = fuelings.all.sum { |f| f.miles }
    base_mileage + computed_miles
  end

  def recent_mileage(num_months)
    recent_fuelings(num_months).sum { |f| f.miles }
  end

  def miles_since_maintenance
    if last_maintenance.present?
      fuelings_since_maintenance = fuelings.where 'date > ?', last_maintenance.date
      fuelings_since_maintenance.sum { |f| f.miles }
    end
  end

  def lifetime_mpg
    fuelings.all.to_a.average { |f| f.mpg } if fuelings.any?
  end

  def recent_mpg(num_months)
    if fuelings.any?
      recent_fuelings(num_months).to_a.average { |f| f.mpg }
    end
  end

  def last_maintenance
    maintenance.order(date: :desc).first
  end

  def line_items
    all_items = fuelings + maintenance
    all_items.sort do |first, second|
      second.date <=> first.date
    end
  end

  private

  def recent_fuelings(num_months)
    recent_fuelings = fuelings.where 'date > ?', num_months.months.ago
  end
end

app/controllers/vehicle_controller.rb
class VehicleController < AuthenticatedController
  before_action :authorize, except: [:new, :create]

  def new
    @vehicle = Vehicle.new
    @action_text = 'Create'
    @action = vehicle_path
    render 'edit'
  end

  def create
    session_manager = Session.new(session)

    new_vehicle = Vehicle.create(vehicle_params)
    new_vehicle.user = session_manager.user
    new_vehicle.save

    redirect_to root_path
  end

  def show
  end

  def edit
    @action_text = 'Save'
    @action = update_vehicle_path
  end

  def update
    @vehicle.update vehicle_params
    flash[:notice] = 'Vehicle updated'
    redirect_to show_vehicle_path(params[:id])
  end

  def destroy
    @vehicle.destroy
    flash[:notice] = 'Vehicle removed'
    redirect_to root_path
  end

  private

  def authorize
    @vehicle = Vehicle.find params[:id]
    session_manager = Session.new(session)
    redirect_to login_path unless session_manager.user_id == @vehicle.user.id
  end

  def vehicle_params
    params.require(:vehicle).permit(:year, :make, :model, :color, :base_mileage)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < AuthorizeVehicleController
  def new
    @vehicle = Vehicle.new
    @action_text = 'Create'
    @action = vehicles_path
    render 'edit'
  end

  def create
    session_manager = Session.new(session)

    new_vehicle = Vehicle.create(vehicle_params)
    new_vehicle.user = session_manager.user
    new_vehicle.save

    redirect_to root_path
  end

  def edit
    @action_text = 'Save'
    @action = vehicle_path params[:id]
  end

  def update
    @vehicle.update vehicle_params
    flash[:notice] = 'Vehicle updated'
    redirect_to vehicle_path(params[:id])
  end

  def destroy
    @vehicle.destroy
    flash[:notice] = 'Vehicle removed'
    redirect_to root_path
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:year, :make, :model, :color, :base_mileage)
  end
end

app/helpers/vehicle_helper.rb
module VehicleHelper
  def pretty_number(num)
    number_with_precision num,
                          delimiter: ',',
                          precision: 2,
                          strip_insignificant_zeros: true
  end

  def react_vehicle(vehicle)
    {
      id: vehicle.id,
      needsMaintenance: vehicle.needs_maintenance?,
      year: vehicle.year,
      make: vehicle.make,
      model: vehicle.model,
      mpg: {
        lifetime: pretty_number(vehicle.lifetime_mpg),
        recent: pretty_number(vehicle.recent_mpg(6.months)),
      },
      mileage: {
        lifetime: pretty_number(vehicle.lifetime_mileage),
        recent: pretty_number(vehicle.recent_mileage(6.months)),
        sinceMaintenance: pretty_number(vehicle.miles_since_maintenance),
      },
      lineItems: vehicle.line_items.map { |item| react_line_item item },
    }
  end

  def react_line_item(line_item)
    type = line_item.class.name.downcase
    react_item = {
      type: type,
      key: type + line_item.id.to_s,
      id: line_item.id,
      date: line_item.date,
    }

    type_specific = type_specific_line_item line_item

    react_item.merge type_specific
  end

  def type_specific_line_item(line_item)
    if (line_item.class == Fueling)
      return react_fueling line_item
    elsif (line_item.class == Maintenance)
      return react_maintenance line_item
    else
      {}
    end
  end

  def react_fueling(fueling)
    {
      aboveAverageMpg: fueling.above_average_mpg?,
      mpg: pretty_number(fueling.mpg),
      miles: pretty_number(fueling.miles),
    }
  end

  def react_maintenance(maintenance)
    {
      needsAttention: maintenance.needs_attention?,
      mechanic: maintenance.mechanic,
      description: maintenance.description,
    }
  end
end

app/views/vehicle/_title.html.erb
<div class="title">
  <h2>
    <span><%= vehicle.year %></span>
    <span><%= vehicle.make %></span>
    <span><%= vehicle.model %></span>
  </h2>
  <div class="buttons">
    <a href="<%= edit_vehicle_path %>" class="btn btn-default">
      <i class="fa fa-edit"></i>
    </a>
    <%= form_tag destroy_vehicle_path, method: 'DELETE', class: 'button_form' do %>
      <button type="submit" class="btn btn-danger">
        <i class="fa fa-times"></i>
      </button>
    <% end %>
  </div>
</div>
<% if vehicle.needs_maintenance? %>
  <div class="important maintenance">
    <i class="fa fa-exclamation-circle"></i>
    Maintenance required!
  </div>
<% end %>

app/views/vehicle/new.html.erb
<div class="new vehicle form">
  <%= form_for @vehicle, url: vehicle_path do |f| %>
    <div class="form-group">
      <%= f.label :year, class: 'control-label' %>:
      <%= f.text_field :year, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :make, class: 'control-label' %>:
      <%= f.text_field :make, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :model, class: 'control-label' %>:
      <%= f.text_field :model, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :color, class: 'control-label' %>:
      <%= f.text_field :color, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :base_mileage, 'Mileage: ', class: 'control-label' %>
      <%= f.text_field :base_mileage, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>